### ISSUE TITLE
Does it work for unicode strings ? (solved

### ISSUE THREAD

**Issue by planetoryd** [VictorBulba/fuzzy_trie#2]
It only works for ASCII but not unicode for me. (it returns results of all the same distance) I'm trying to write a dictionary

**Comment by planetoryd** [comment]
I enabled `damerau` and now it works

**Comment by VictorBulba** [comment]
Hmm, should work either way

**Comment by VictorBulba** [comment]
https://github.com/VictorBulba/fuzzy_trie/blob/master/src/tests.rs#L69L87

Added a test for unicode strings

**Comment by planetoryd** [comment]
It’s a serialization issue. I added serde derive to it, and used flexbuffers. It doesn't work when deserializing from disk. 

Something must have changed during the process. It works with yaml

**Comment by planetoryd** [comment]
now use cbor
